[model]
max_context_len = 336
max_pred_len = 168
# 输入输出长度
context_len = 168
pred_len = 24

# TimeMixer 核心参数
d_model = 768
d_ff = 2048
e_layers = 10
down_sampling_layers = 2
down_sampling_window = 2
down_sampling_method = "avg"

# 分解方式
moving_avg = 25
decomp_method = "moving_avg"   # 可改成 "dft_decomp"
top_k = 5

# 嵌入与正则
embed = "timeF"
freq = "h"
dropout = 0.1

# 通道与其他
enc_in = 1
c_out = 1
channel_independence = 0
use_norm = 1
use_future_temporal_feature = false

# 损失相关
huber_delta = 1.0
continuous_loads = true


[pretrain]
batch_size = 32
init_scale = 0.02
warmup_steps = 10000
lr = 0.00006
train_tokens = 2000000000
eval_every = 200
apply_scaler_transform = 'boxcox'
note = ''

[zero_shot]
apply_scaler_transform = 'boxcox'

[transfer_learning]
apply_scaler_transform = 'boxcox'
